
export const ResponseMessage = {
  usernotfound: 'User not found!',
  unknown: 'Something bad happened!; Please try again!',
  invalidlogin: 'Invalid login!',
  invalidcredentials: 'Invalid credentials!',
  invalidotp: 'Invalid OTP!',
  otpexpired: 'OTP expired!',
  otpverified: 'OTP verified successfully!',
  passwordencryptfailed: 'Password encryption failed!',
  passwordresetfailed: 'Password reset failed!',
  passwordreset: 'Password reset successfully!',
  loginsuccess: 'Login successful!',
  verificationcodesent: 'Verification code sent to email!',
  emailnotsent: 'Email not sent!',
  emailtemplatesmissing: 'Email templates are missing!',
  emailnotsupported: 'Email service not supported!',
  emailconfigmissing: 'Email configuration is missing!',
  emailnotsentinvalid: 'Email not sent! Invalid email address.',
  emailnotsentfailed: 'Email not sent! Failed to send email.',
  usercreate: 'User Created Successfully!',
  userupdate: 'User Updated Successfully!',
  userdelete: 'User Deleted Successfully!',
  usercreatefailed: 'User Created Failed!',
  userexists: 'User already exists!',
  userfound: 'User found!',
  usersfound: 'Users found!',
  usersnotfound: 'No users found!',
  userupdatefailed: 'User Update Failed!',
  userdeletefailed: 'User Delete Failed!',
  userfetchfailed: 'User fetch failed!',
  rolecreate: 'Role Created Successfully!',
  rolecreatefailed: 'Role Create Failed!',
  roleexists: 'Role already exists!',
  rolefound: 'Role found!',
  rolesfound: 'Roles found!',
  rolesnotfound: 'No roles found!',
  roleupdate: 'Role Updated Successfully!',
  roleupdatefailed: 'Role Update Failed!',
  roledelete: 'Role Deleted Successfully!',
  roledeletefailed: 'Role Delete Failed!',
  rolenotfound: 'Role not found!',
  rolefetchfailed: 'Role fetch failed!',
};

export const SKIP_TOKEN_AUTH_ROUTES = [
  '/auth/login',
  '/auth/forget-password',
  '/email/send-email',
  '/auth/send-otp',
  '/users/create' //Remove this in production
];
